### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Simonesien** [DMBuce/mcexplore#6]
Hello!
I would appreciate it if you make a parameter for your script like `--StartMinecraftServerIfLevel.datFileDoesNotExist`.
I think it would be a great feature because I believe that many Server Admins have build their own script to start the Minecraft Server once and then run mcexplore to expand the world in order to have a custom seed pregenerated on demand. So with this feature, we won't have to code the same thing, running the Minecraft Server to generate Minecraft Terrain, twice. And because you have already coded the stuff about the communication with the Server (Starting and Stopping), it would be great if you install this feature in your script. 
It would also be helpful for newcomers. 
Greetings, Simon

**Comment by DMBuce** [comment]
I just pushed a new version that should start and stop the server if server.properties or level.dat do not exist. It also exits with an error if a line with "eula=false" exists in eula.txt .

No option flags needed, it just tries to do the right thing.

**Comment by Simonesien** [comment]
Hello!
First I want to say, that I'm very impressed of the speed of your work. Now when there isn't a server.properties or a level.dat file, mcexplore starts the Minecraft Server to generate them and that was what I wanted. But I would suggest you not to check if there is a file named server.properties, but to check if there is a world folder with the right content in it. 

Also I wondered why this gives an error: 
```
pi@minepi:~/minecraft-server/rwt $ ls -al
total 12
drwxr-xr-x  2 pi pi 4096 Oct  7 18:51 .
drwxr-xr-x 17 pi pi 4096 Oct  7 18:50 ..
-rw-r--r--  1 pi pi   10 Oct  7 18:50 eula.txt
lrwxrwxrwx  1 pi pi   36 Oct  7 18:50 server.jar -> /home/pi/minecraft-server/1.16.4.jar
-rw-r--r--  1 pi pi    0 Oct  7 18:50 server.properties
pi@minepi:~/minecraft-server/rwt $ python3 /home/pi/minecraft-server/mcexplore.py -c "java -Xmx2560M -jar server.jar nogui" -p /home/pi/minecraft-server/rwt 28
Traceback (most recent call last):
  File "/home/pi/minecraft-server/mcexplore.py", line 364, in <module>
    main()
  File "/home/pi/minecraft-server/mcexplore.py", line 194, in main
    world = os.path.join(options.path, properties['level-name'])
KeyError: 'level-name'
pi@minepi:~/minecraft-server/rwt $ 
```
(server.jar is operating perfectly and in eula.txt there is `eula=true`)
Ok, I not exactly wondered, my explanation for it is, that mcexplore cannot handle, that server.properties exist, but level.dat not.

Thanks for looking around this Feature Request, Simon :)

**Comment by DMBuce** [comment]
The path to level.dat depends on the value of `level-name` in server.properties. So mcexplore needs server.properties to exist with `level-name` defined in it before it can check level.dat.

Is `level-name` defined in your server.properties? The error you showed makes me think that it isn't. Either set `level-name` to the name of your world folder (default is `level-name=world`) or remove server.properties so that the server jar can regenerate it.

**Comment by DMBuce** [comment]
I just pushed a change so that mcexplore will check to make sure `level-name` is defined in server.properties instead of dumping a stack trace with `KeyError: 'level-name'`. If `level-name` isn't defined, mcexplore will start and stop the server in order to populate server.properties with default values, then it will check for `level-name` again and exit with an error if it still isn't defined.

HTH

**Comment by Simonesien** [comment]
Thanks. You have helped me a lot to save time messing up with my script.
